version: '3.9'
services:
  todo-app:
    container_name: todo-app
    build:
      context: .
    depends_on:
      - todo-db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - todo-network

  todo-db:
    container_name: todo-db
    image: mysql:8.0.29-oracle
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "todo"
      MYSQL_USER: "todo"
      MYSQL_PASSWORD: "todo"
    ports:
      - "3309:3306"
    networks:
      - todo-network

networks:
  todo-network:
    name: todo-network
    driver: bridge
